# FOT08: ¿Cual es el estado operativo de la instalación fotovoltaica?

PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX edintfot: <http://vocab.linkeddata.es/datosabiertos/def/energia-medioambiente/fotovoltaica#>

SELECT ?pvSystem ?status ?statusLabel
WHERE {
  ?pvSystem a edintfot:PhotovoltaicSystem ;
            edintfot:hasStatus ?status .
  OPTIONAL { ?status skos:prefLabel ?statusLabel . }
}
ORDER BY ?pvSystem